data:
    name: mnist
    batch_size: 128
    num_workers: 1

model:
    name: resnet18
    conv:
        kernel_size: 3
        stride: 1
        padding: 1
    maxpool: null
    avgpool:
        kernel_size: 4

optimizer:
    name: sgd
    lr: 0.005
    momentum: 0.9
    weight_decay: 'overwrite-me'
    
model_seed: 1
sampler_seed: 1
