data:
    name: wmnist
    batch_size: 128
    num_workers: 0
    whitening_level: 'overwrite-me'

model:
    name: resnet50
    conv:
        kernel_size: 3
        stride: 1
        padding: 1
    maxpool: null
    avgpool:
        kernel_size: 4

optimizer:
    name: sgd
    lr: 0.01
    momentum: 0.9
    
model_seed: 1
sampler_seed: 1
