data:
    name: mnist
    batch_size: 128
    num_workers: 1

model:
    name: vgg11
    batch_norm: True

optimizer:
    name: sgd
    lr: 0.005
    momentum: 0.9
    weight_decay: 'overwrite-me'
    
model_seed: 1
sampler_seed: 1
