data:
    name: cifar10
    batch_size: 128
    num_workers: 1

    wrapper:
        name: shuffling
        target: target
        level: 'overwrite-me'

model:
    name: mlp
    layers:
        - 1000
        - 500
        - 300
        - 200
        - 100

optimizer:
    name: sgd
    lr: 0.01
    momentum: 0.0
    
model_seed: 1
sampler_seed: 1
