stages:
  - build
  - pretest
  - test
  - deploy

image: python:3.6

before_script:
  - python --version
  - pip install tox
  - pip install --upgrade setuptools>=40.1.0

# build:
#   type: build
#   script:
#   - python --version

# flake8:
#   type: pretest
#   script: tox -e flake8

# pylint:
#   type: pretest
#   script: tox -e pylint

py36:
  type: test
  script: tox -e py36  # -c 'print("pytest")'
  after_script:
    - tox -e final-coverage
    - tox -e codecov

singularity:
  stage: deploy
  script:
    - flow-deploy . SingularityTemplate --use-commit-checksum
        --singularity-repo https://github.com/bouthilx/sgd-space-hub.git
