stages:
  - build
  - pretest
  - test
  - deploy

build:
  type: build
  script:
    apt-get update -qy
    python --version # -c 'print("Hello world")'

flake8:
  type: pretest
  image: python:3.6
  script: tox -e flake8

# pylint:
#   type: pretest
#   image: python:3.6
#   script: tox -e pylint

py36:
  type: test
  script: python --version  # -c 'print("pytest")'

packaging:
  stage: deploy
  script: python --version  # -c 'print("deploying")'
