data:
    name: svhn
    batch_size: 128
    num_workers: 5

model:
    name: mobilenetv2
    conv:
      kernel_size: 3
      stride: 1
      padding: 1
    avgpool:
      kernel_size: 4

optimizer:
    name: sgd
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0005
    
model_seed: 'overwrite-me'
sampler_seed: 'overwrite-me'
