data:
    pump_out: 1000
    batch_size: 1
    model:
        select:
            - train
            - valid
            - test

seed: 1

query:
    epoch: 'overwrite-me'

analyses:
    bd_participation_ratio:
        movement_samples: 100
        centered: True
        optimizer_params:
            lr: 1.0
            momentum: 0.0
