data:
    pump_out: 1000
    model:
        select:
            - train
            - valid
            - test

seed: 1

query:
    epoch: 'overwrite-me'

analyses:
    bd_participation_ratio:
        movement_samples: 100
        at_origin: True
        center: False
        normalize: True
        batch_size: null
        optimizer_params: {}
