data:
    pump_out: 1000
    model:
        select:
            - train
            - valid
            - test
    sphericalcow:
        select:
            - train
            - valid
            - test
    shuffling10:
        name: shuffling
        select:
            - train
            - valid
            - test
        target: target
        level: 1.0

query:
    epoch: 'overwrite-me'

analyses:
    - bd_participation_ratio:
        movement_samples: 100
        centered: False
        optimizer_params: {}
