data:
    model:
        select:
            - train
            - valid
            - test

seed: 1

query:
    epoch: 'overwrite-me'

analyses:
    spectral_norm:
        n_power_iterations: 200
        eps: 1.0e-12
