data:
    model:
        select:
            - train
            - valid
            - test
    sphericalcow:
        select:
            - train
            - valid
            - test
    shuffling10:
        name: shuffling
        select:
            - train
            - valid
            - test
        target: target
        level: 1.0

seed: 1

query:
    epoch: 'overwrite-me'

analyses:
    - spectral_norm:
        n_power_iterations: 200
        eps: 1.0e-12
