data:
    pump_out: 1000
    model:
        select:
            - train

seed: 1

query:
    epoch: 'overwrite-me'

analyses:
    truncated_bd_participation_ratio:
        movement_samples: null
        centered: False
        batch_size: null
        optimizer_params: {}
