data:
    name: mnist
    batch_size: 128
    num_workers: 0

model:
    name: resnet18
    conv:
        kernel_size: 3
        stride: 1
        padding: 1
    maxpool: null
    avgpool:
        kernel_size: 4

optimizer:
    name: sgd
    lr: 'orion~loguniform(0.001,1.0)'
    momentum: 'orion~uniform(0.0, 1.0)'
    weight_decay: 'orion~loguniform(1e-8, 0.1)'
   
model_seed: 1
sampler_seed: 1
