data:
    name: gaussian
    width: 10
    size: 1000
    classes: 5
    batch_size: 128

    wrapper:
        name: shuffling
        target: target
        level: 'overwrite-me'

model:
    name: mlp
    bias: False
    layers:
        - 100

optimizer:
    name: sgd
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0005
    
model_seed: 1
sampler_seed: 1
