data:
    name: gaussian
    width: 10
    size: 1000
    classes: 5
    batch_size: 128

    wrapper:
        name: shuffling
        target: target
        level: 'overwrite-me'

model:
    name: mlp
    layers:
        - 200
        - 200

optimizer:
    name: sgd
    lr: 0.01
    momentum: 0.0
    
model_seed: 1
sampler_seed: 1
