name: bayesopt
max_trials: 100
strategy: cl_min
n_initial_points: 10
acq_func: gp_hedge
alpha: 1.0e-10
n_restarts_optimizer: 0
normalize_y: False
noise: gaussian
# Add noise option here:
# https://github.com/Epistimio/orion.algo.skopt/blob/master/src/orion/algo/skopt/bayes.py#L137
