data:
    name: gaussian
    width: 10
    size: 1000
    classes: 5
    batch_size: 128

model:
    name: mlp
    layers:
        - 200
        - 200

optimizer:
    name: sgd
    lr: 'orion~loguniform(0.001,1.0)'
    momentum: 'orion~uniform(0.0, 1.0)'
    weight_decay: 'orion~loguniform(1e-8, 0.1)'
    
model_seed: 1
sampler_seed: 1
