data:
    name: cifar10
    batch_size: 128
    num_workers: 1

model:
    name: mlp
    bias: False
    layers:
        - 500
        - 500

optimizer:
    name: sgd
    lr: 0.001
    momentum: 0.9
    weight_decay: 'overwrite-me'
    
model_seed: 1
sampler_seed: 1
