data:
    name: wcifar10
    batch_size: 128
    num_workers: 0
    whitening_level: 'overwrite-me'

model:
    name: vgg19
    batch_norm: True

optimizer:
    name: sgd
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0005
    
model_seed: 1
sampler_seed: 1
