data:
    name: cifar10
    batch_size: 128
    num_workers: 1

    wrapper:
        name: shuffling
        target: target
        level: 'orion~choices([0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0])'

model:
    name: mlp
    layers:
        - 1000
        - 500
        - 100

optimizer:
    name: sgd
    lr: 0.01
    momentum: 0.0
    
model_seed: 1
sampler_seed: 1
