data:
    name: tinyimagenet
    batch_size: 128
    num_workers: 5

model:
    distributed: 1
    name: densenet161

optimizer:
    name: sgd
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0001
    
model_seed: 'overwrite-me'
sampler_seed: 'overwrite-me'
