data:
    name: tinyimagenet
    batch_size: 128
    num_workers: 5

model:
    distributed: 1
    name: resnet34
    conv:
        kernel_size: 7
        stride: 2
        padding: 3
    maxpool:
        kernel_size: 3
        stride: 2
        padding: 1
    avgpool:
        kernel_size: 4

optimizer:
    name: sgd
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0001
    
model_seed: 'overwrite-me'
sampler_seed: 'overwrite-me'
