data:
    name: mnist
    batch_size: 128
    num_workers: 5

model:
    name: preactresnet50
    conv:
        kernel_size: 3
        stride: 1
        padding: 1
    maxpool: null
    avgpool:
        kernel_size: 4

optimizer:
    name: sgd
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0001
    
model_seed: 'overwrite-me'
sampler_seed: 'overwrite-me'
