data:
    name: mnist
    batch_size: 128
    num_workers: 1

    wrapper:
        name: shuffling
        target: target
        level: 'overwrite-me'

model:
    name: mlp
    layers:
        - 500
        - 500

optimizer:
    name: sgd
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0005

model_seed: 1
sampler_seed: 1
