data:
    name: wcifar10
    batch_size: 128
    num_workers: 0
    epsilon: 'overwrite-me'

model:
    name: resnet18
    conv:
        kernel_size: 3
        stride: 1
        padding: 1
    maxpool: null
    avgpool:
        kernel_size: 4

optimizer:
    name: sgd
    lr: 0.005
    momentum: 0.9
    weight_decay: 0.0005
    
model_seed: 1
sampler_seed: 1
