data:
    name: gaussian
    width: 10
    size: 1000
    classes: 5
    batch_size: 128

model:
    name: mlp
    bias: False
    layers:
        - 200
        - 200

optimizer:
    name: sgd
    lr: 0.1
    momentum: 0.9
    weight_decay: 'overwrite-me'
    
model_seed: 1
sampler_seed: 1
